language: php
dist: focal

php:
  - 8.2

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false